"use client";
import { useEffect, useState } from "react";
import { PageHeading } from "@/components/shared/page-heading";
type Mapping = { email: string; firstName: string; lastName: string; phone: string; jobTitle: string; companyName: string; companyDomain: string; status: string; score: string };
type Provider = "MOCK" | "HUBSPOT";
type Connection = { id: string; provider: Provider; displayName: string; isActive: boolean; fieldMapping: Mapping; lastTestedAt: string | null; _count?: { contactLinks: number; syncAttempts: number } };
type Sync = { id: string; status: string; error: string | null; startedAt: string; lead: { id: string; firstName: string | null; lastName: string | null; email: string | null; companyName: string | null } };
const labels: Record<keyof Mapping, string> = { email: "Email", firstName: "First name", lastName: "Last name", phone: "Phone", jobTitle: "Job title", companyName: "Company", companyDomain: "Company website", status: "Lead status", score: "Lead score" };
const defaultMapping: Mapping = { email: "email", firstName: "firstname", lastName: "lastname", phone: "phone", jobTitle: "jobtitle", companyName: "company", companyDomain: "website", status: "", score: "" };
const initial = { provider: "MOCK" as Provider, displayName: "Development CRM", isActive: true, fieldMapping: defaultMapping };
async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Request failed."); return body.data as T; }
export function CrmManager({ canManage }: { canManage: boolean }) {
  const [connection, setConnection] = useState<Connection | null>(null); const [form, setForm] = useState(initial); const [syncs, setSyncs] = useState<Sync[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const [saved, history] = await Promise.all([request<Connection | null>("/api/crm/connection"), request<Sync[]>("/api/crm/syncs")]); setConnection(saved); setSyncs(history); if (saved) setForm({ provider: saved.provider, displayName: saved.displayName, isActive: saved.isActive, fieldMapping: saved.fieldMapping }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load CRM settings."); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { await request("/api/crm/connection", { method: "PUT", body: JSON.stringify(form) }); await load(); setMessage(form.provider === "HUBSPOT" ? "HubSpot connection saved. Test it before syncing leads." : "Mock CRM connection saved. No external service received data."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save connection."); } finally { setBusy(false); } }
  async function test() { setBusy(true); setMessage(""); try { await request("/api/crm/connection/test", { method: "POST" }); await load(); setMessage(`${connection?.provider === "HUBSPOT" ? "HubSpot" : "Mock CRM"} connection test passed.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Connection test failed."); } finally { setBusy(false); } }
  return <section className="page crm-page"><PageHeading eyebrow="INTEGRATIONS" title="CRM synchronization" description="Map LeadFlow contacts and track every create or update attempt." action={connection && <span className={`crm-connection-status ${connection.isActive ? "active" : ""}`}>{connection.isActive ? "Active" : "Disabled"}</span>} />
    <div className="crm-safety"><span>◇</span><div><strong>{form.provider === "HUBSPOT" ? "Real HubSpot synchronization" : "Development-safe mock provider"}</strong><p>{form.provider === "HUBSPOT" ? "Lead data is sent to HubSpot only when a user explicitly syncs a lead. The access token stays on the server." : "The mock provider records deterministic CRM IDs locally. It never transfers lead data outside LeadFlow."}</p></div></div>
    {!canManage && <div className="inline-error">Your role can view CRM history, but only owners and admins can configure the connection.</div>}
    {canManage && <form className="panel crm-settings" onSubmit={save}><header><div><h2>CRM connection</h2><p>Choose a local test provider or connect this deployment to HubSpot.</p></div><span>{form.provider}</span></header><div className="crm-config-grid"><label>Provider<select value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value as Provider, displayName: event.target.value === "HUBSPOT" ? "HubSpot" : "Development CRM", fieldMapping: defaultMapping })}><option value="MOCK">Mock CRM (local testing)</option><option value="HUBSPOT">HubSpot</option></select></label><label>Connection name<input required value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /></label><label className="crm-toggle"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /><span><strong>Enable synchronization</strong><small>Allows members to sync individual leads.</small></span></label></div>{form.provider === "HUBSPOT" && <p className="crm-mapping-help">Set <code>HUBSPOT_ACCESS_TOKEN</code> in the server environment with contacts read/write access. It is never stored in the browser or database.</p>}<h3>Contact field mapping</h3><p className="crm-mapping-help">Choose the provider property for each LeadFlow field. Leave optional mappings blank to skip them.</p><div className="crm-mapping">{Object.entries(labels).map(([source, label]) => <label key={source}><span>{label}<small>LeadFlow: {source}</small></span><input required={source === "email"} value={form.fieldMapping[source as keyof Mapping]} onChange={(event) => setForm({ ...form, fieldMapping: { ...form.fieldMapping, [source]: event.target.value } })} /></label>)}</div><footer><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save connection"}</button><button className="secondary-button" type="button" disabled={busy || !connection} onClick={() => void test()}>Test connection</button>{connection?.lastTestedAt && <small>Last tested {new Date(connection.lastTestedAt).toLocaleString()}</small>}</footer></form>}
    {message && <div className="scoring-message" role="status">{message}</div>}
    <section className="panel crm-history"><header><div><h2>Synchronization history</h2><p>Latest 100 attempts, newest first.</p></div><span>{connection?._count?.contactLinks ?? 0} linked contacts</span></header>{syncs.length ? <div>{syncs.map((sync) => <article key={sync.id}><span className={`crm-sync-icon ${sync.status.toLowerCase()}`}>{sync.status === "COMPLETED" ? "✓" : sync.status === "FAILED" ? "!" : "…"}</span><div><strong>{[sync.lead.firstName, sync.lead.lastName].filter(Boolean).join(" ") || sync.lead.email}</strong><small>{sync.lead.companyName || sync.lead.email}</small></div><span className={`crm-sync-status ${sync.status.toLowerCase()}`}>{sync.status}</span><time>{new Date(sync.startedAt).toLocaleString()}</time></article>)}</div> : <p className="crm-empty">No CRM synchronization attempts yet. Open a lead to sync it.</p>}</section>
  </section>;
}
