ALTER TYPE "LeadActivityType" ADD VALUE 'CRM_SYNCED';
ALTER TYPE "LeadActivityType" ADD VALUE 'CRM_SYNC_FAILED';
CREATE TYPE "CrmProviderType" AS ENUM ('MOCK', 'HUBSPOT');
CREATE TYPE "CrmSyncStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED');
CREATE TABLE "CrmConnection" ("id" TEXT NOT NULL,"provider" "CrmProviderType" NOT NULL DEFAULT 'MOCK',"displayName" TEXT NOT NULL DEFAULT 'Development CRM',"isActive" BOOLEAN NOT NULL DEFAULT true,"fieldMapping" JSONB NOT NULL,"lastTestedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"workspaceId" TEXT NOT NULL,CONSTRAINT "CrmConnection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CrmContactLink" ("id" TEXT NOT NULL,"externalId" TEXT NOT NULL,"lastSyncedAt" TIMESTAMP(3) NOT NULL,"sourceUpdatedAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"workspaceId" TEXT NOT NULL,"connectionId" TEXT NOT NULL,"leadId" TEXT NOT NULL,CONSTRAINT "CrmContactLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CrmSyncAttempt" ("id" TEXT NOT NULL,"status" "CrmSyncStatus" NOT NULL DEFAULT 'PENDING',"idempotencyKey" TEXT NOT NULL,"operation" TEXT NOT NULL DEFAULT 'UPSERT_CONTACT',"requestPayload" JSONB NOT NULL,"responsePayload" JSONB,"error" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"workspaceId" TEXT NOT NULL,"connectionId" TEXT NOT NULL,"leadId" TEXT NOT NULL,"initiatedById" TEXT,CONSTRAINT "CrmSyncAttempt_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CrmConnection_workspaceId_key" ON "CrmConnection"("workspaceId");
CREATE UNIQUE INDEX "CrmContactLink_connectionId_leadId_key" ON "CrmContactLink"("connectionId", "leadId");
CREATE UNIQUE INDEX "CrmContactLink_connectionId_externalId_key" ON "CrmContactLink"("connectionId", "externalId");
CREATE INDEX "CrmContactLink_workspaceId_lastSyncedAt_idx" ON "CrmContactLink"("workspaceId", "lastSyncedAt");
CREATE UNIQUE INDEX "CrmSyncAttempt_idempotencyKey_key" ON "CrmSyncAttempt"("idempotencyKey");
CREATE INDEX "CrmSyncAttempt_workspaceId_startedAt_idx" ON "CrmSyncAttempt"("workspaceId", "startedAt");
CREATE INDEX "CrmSyncAttempt_leadId_startedAt_idx" ON "CrmSyncAttempt"("leadId", "startedAt");
CREATE INDEX "CrmSyncAttempt_connectionId_status_idx" ON "CrmSyncAttempt"("connectionId", "status");
ALTER TABLE "CrmConnection" ADD CONSTRAINT "CrmConnection_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmContactLink" ADD CONSTRAINT "CrmContactLink_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmContactLink" ADD CONSTRAINT "CrmContactLink_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "CrmConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmContactLink" ADD CONSTRAINT "CrmContactLink_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmSyncAttempt" ADD CONSTRAINT "CrmSyncAttempt_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmSyncAttempt" ADD CONSTRAINT "CrmSyncAttempt_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "CrmConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmSyncAttempt" ADD CONSTRAINT "CrmSyncAttempt_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmSyncAttempt" ADD CONSTRAINT "CrmSyncAttempt_initiatedById_fkey" FOREIGN KEY ("initiatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
