import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import { CrmProviderType, LeadSourceType, LeadStatus, WorkspaceRole } from "@/generated/prisma/enums";
import type { CrmProvider } from "@/lib/crm/provider";
import { defaultCrmFieldMapping, saveCrmConnection, syncLeadToCrm, testCrmConnection } from "@/lib/crm/service";
import type { LeadServiceContext } from "@/lib/leads/service";

const connectionString = process.env.DATABASE_URL; if (!connectionString) throw new Error("DATABASE_URL is required for database integration tests.");
const pool = new Pool({ connectionString }); const database = new PrismaClient({ adapter: new PrismaPg(pool) }); const runId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
let workspaceId = ""; let owner: LeadServiceContext; let member: LeadServiceContext; let viewer: LeadServiceContext;
beforeAll(async () => { const workspace = await database.workspace.create({ data: { name: "CRM test", slug: `crm-${runId}` } }); const users = await Promise.all(["owner", "member", "viewer"].map((name) => database.user.create({ data: { email: `crm-${name}-${runId}@example.test` } }))); await database.workspaceMember.createMany({ data: [{ workspaceId: workspace.id, userId: users[0].id, role: WorkspaceRole.OWNER }, { workspaceId: workspace.id, userId: users[1].id, role: WorkspaceRole.MEMBER }, { workspaceId: workspace.id, userId: users[2].id, role: WorkspaceRole.VIEWER }] }); workspaceId = workspace.id; owner = { workspaceId, userId: users[0].id, role: WorkspaceRole.OWNER }; member = { workspaceId, userId: users[1].id, role: WorkspaceRole.MEMBER }; viewer = { workspaceId, userId: users[2].id, role: WorkspaceRole.VIEWER }; });
afterAll(async () => { await database.workspace.deleteMany({ where: { id: workspaceId } }); await database.user.deleteMany({ where: { email: { contains: runId } } }); await database.$disconnect(); await pool.end(); });
async function lead(label: string) { return database.lead.create({ data: { workspaceId, email: `${label}-${runId}@example.test`, firstName: "Maya", companyName: "Acme", status: LeadStatus.QUALIFIED, source: LeadSourceType.MANUAL } }); }

describe("CRM synchronization foundation", () => {
  it("restricts configuration to managers and tests the mock connection", async () => { const input = { provider: CrmProviderType.MOCK, displayName: "Sales CRM", isActive: true, fieldMapping: defaultCrmFieldMapping }; await expect(saveCrmConnection(database, viewer, input)).rejects.toMatchObject({ status: 403 }); expect((await saveCrmConnection(database, owner, input)).provider).toBe("MOCK"); expect((await testCrmConnection(database, owner)).provider).toBe("mock"); });
  it("creates one link and makes an unchanged sync idempotent", async () => { const target = await lead("idempotent"); const first = await syncLeadToCrm(database, member, target.id); const second = await syncLeadToCrm(database, member, target.id); expect(first.duplicate).toBe(false); expect(second.duplicate).toBe(true); expect(second.link?.externalId).toBe(first.link?.externalId); expect(await database.crmSyncAttempt.count({ where: { leadId: target.id } })).toBe(1); expect(await database.leadActivity.count({ where: { leadId: target.id, type: "CRM_SYNCED" } })).toBe(1); await expect(syncLeadToCrm(database, viewer, target.id)).rejects.toMatchObject({ status: 403 }); });
  it("updates the existing CRM contact after a lead changes", async () => { const target = await lead("update"); const first = await syncLeadToCrm(database, owner, target.id); await database.lead.update({ where: { id: target.id }, data: { jobTitle: "Founder" } }); const second = await syncLeadToCrm(database, owner, target.id); expect(second.duplicate).toBe(false); expect(second.link?.externalId).toBe(first.link?.externalId); expect(await database.crmContactLink.count({ where: { leadId: target.id } })).toBe(1); expect(await database.crmSyncAttempt.count({ where: { leadId: target.id } })).toBe(2); });
  it("records provider failure and permits retry with the same key", async () => { const target = await lead("failure"); const failing: CrmProvider = { name: "test", async testConnection() { return { ok: true, provider: "test" }; }, async upsertContact() { throw new Error("Temporary CRM outage"); } }; await expect(syncLeadToCrm(database, owner, target.id, failing)).rejects.toMatchObject({ code: "CRM_SYNC_FAILED" }); expect(await database.leadActivity.findFirst({ where: { leadId: target.id, type: "CRM_SYNC_FAILED" } })).not.toBeNull(); const retry = await syncLeadToCrm(database, owner, target.id); expect(retry.attempt.status).toBe("COMPLETED"); expect(await database.crmSyncAttempt.count({ where: { leadId: target.id } })).toBe(1); });
});
