"use client";
import { useEffect, useState } from "react";
import { PageHeading } from "@/components/shared/page-heading";

type Interval = { start: string; end: string }; type Availability = Record<string, Interval[]>;
type Page = { publicId: string; title: string; description: string | null; durationMinutes: number; bufferMinutes: number; minimumNoticeHours: number; maximumAdvanceDays: number; timeZone: string; availability: Availability; isActive: boolean };
type Meeting = { id: string; startAt: string; endAt: string; attendeeName: string; attendeeEmail: string; attendeeTimeZone: string; lead: { id: string; firstName: string | null; lastName: string | null; email: string | null; companyName: string | null }; bookingPage: { title: string } };
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const defaultAvailability: Availability = { "0": [], "1": [{ start: "09:00", end: "17:00" }], "2": [{ start: "09:00", end: "17:00" }], "3": [{ start: "09:00", end: "17:00" }], "4": [{ start: "09:00", end: "17:00" }], "5": [{ start: "09:00", end: "17:00" }], "6": [] };
const initial = { title: "Book a meeting", description: "Choose a convenient time to speak with our team.", durationMinutes: 30, bufferMinutes: 0, minimumNoticeHours: 2, maximumAdvanceDays: 30, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone, availability: defaultAvailability, isActive: true };
async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Request failed."); return body.data as T; }

export function BookingManager({ canManage }: { canManage: boolean }) {
  const [page, setPage] = useState<Page | null>(null); const [form, setForm] = useState(initial); const [meetings, setMeetings] = useState<Meeting[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const [saved, upcoming] = await Promise.all([request<Page | null>("/api/booking-page"), request<Meeting[]>("/api/meetings")]); setPage(saved); setMeetings(upcoming); if (saved) setForm({ ...saved, description: saved.description ?? "" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load booking settings."); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const saved = await request<Page>("/api/booking-page", { method: "PUT", body: JSON.stringify({ ...form, description: form.description || null }) }); setPage(saved); setMessage("Booking page saved. The public link is ready to share."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save booking page."); } finally { setBusy(false); } }
  function toggle(day: string) { const current = form.availability[day] ?? []; setForm({ ...form, availability: { ...form.availability, [day]: current.length ? [] : [{ start: "09:00", end: "17:00" }] } }); }
  function changeTime(day: string, field: "start" | "end", value: string) { setForm({ ...form, availability: { ...form.availability, [day]: [{ ...(form.availability[day]?.[0] ?? { start: "09:00", end: "17:00" }), [field]: value }] } }); }
  const publicUrl = page ? `${window.location.origin}/book/${page.publicId}` : "";
  return <section className="page booking-page"><PageHeading eyebrow="CALENDAR" title="Meeting booking" description="Publish availability and turn booked conversations into lead activity." action={page && <a className="secondary-button" href={publicUrl} target="_blank" rel="noreferrer">Open public page</a>} />
    {!canManage && <div className="inline-error">Your role can view meetings, but only owners and admins can configure booking.</div>}
    {canManage && <form className="panel booking-settings" onSubmit={save}><div className="booking-config"><h2>Booking page</h2><label>Public title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Description<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div className="booking-options"><label>Duration<select value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: Number(event.target.value) })}>{[15,30,45,60].map((value) => <option key={value} value={value}>{value} minutes</option>)}</select></label><label>Buffer<select value={form.bufferMinutes} onChange={(event) => setForm({ ...form, bufferMinutes: Number(event.target.value) })}>{[0,5,10,15,30].map((value) => <option key={value} value={value}>{value} minutes</option>)}</select></label><label>Minimum notice<input type="number" min="0" max="168" value={form.minimumNoticeHours} onChange={(event) => setForm({ ...form, minimumNoticeHours: Number(event.target.value) })} /></label><label>Booking window<input type="number" min="1" max="180" value={form.maximumAdvanceDays} onChange={(event) => setForm({ ...form, maximumAdvanceDays: Number(event.target.value) })} /></label></div><label>Booking time zone<input required value={form.timeZone} onChange={(event) => setForm({ ...form, timeZone: event.target.value })} /></label><label className="booking-active"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /> Accept new bookings</label>{page && <div className="booking-link"><span>{publicUrl}</span><button type="button" onClick={() => void navigator.clipboard.writeText(publicUrl)}>Copy link</button></div>}<button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save booking page"}</button></div>
      <div className="availability-editor"><h2>Weekly availability</h2><p>Times use {form.timeZone || "your selected time zone"}.</p>{days.map((name, index) => { const active = Boolean(form.availability[String(index)]?.length); return <div className="availability-day" key={name}><label><input type="checkbox" checked={active} onChange={() => toggle(String(index))} /><strong>{name}</strong></label>{active ? <div><input type="time" value={form.availability[String(index)][0].start} onChange={(event) => changeTime(String(index), "start", event.target.value)} /><span>to</span><input type="time" value={form.availability[String(index)][0].end} onChange={(event) => changeTime(String(index), "end", event.target.value)} /></div> : <span>Unavailable</span>}</div>; })}</div></form>}
    {message && <div className="scoring-message" role="status">{message}</div>}
    <section className="panel upcoming-meetings"><header><div><h2>Upcoming meetings</h2><p>Booked conversations across this workspace.</p></div><span>{meetings.length}</span></header>{meetings.length ? meetings.map((meeting) => <article key={meeting.id}><time><strong>{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(meeting.startAt))}</strong><span>{new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", timeZoneName: "short" }).format(new Date(meeting.startAt))}</span></time><div><strong>{meeting.attendeeName}</strong><span>{meeting.attendeeEmail}</span></div><a href={`/leads?lead=${meeting.lead.id}`}>View lead →</a></article>) : <p className="booking-empty">No upcoming meetings yet.</p>}</section>
  </section>;
}
