"use client";
import { useState } from "react";

type PublicPage = { publicId: string; title: string; description: string | null; durationMinutes: number; timeZone: string; maximumAdvanceDays: number; workspace: { name: string } };
async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Request failed."); return body.data as T; }
export function PublicBookingForm({ page, today, maxDate }: { page: PublicPage; today: string; maxDate: string }) {
  const [date, setDate] = useState(today); const [slots, setSlots] = useState<string[]>([]); const [selected, setSelected] = useState(""); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [booked, setBooked] = useState<string | null>(null);
  const viewerTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  async function findSlots(nextDate = date) { setLoading(true); setError(""); setSelected(""); try { const result = await request<{ slots: string[] }>(`/api/public/bookings/${page.publicId}?date=${nextDate}`); setSlots(result.slots); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load times."); } finally { setLoading(false); } }
  async function book(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { await request(`/api/public/bookings/${page.publicId}`, { method: "POST", body: JSON.stringify({ startAt: selected, attendeeName: data.get("name"), attendeeEmail: data.get("email"), attendeeTimeZone: viewerTimeZone, notes: data.get("notes") || null }) }); setBooked(selected); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to book this meeting."); await findSlots(); } finally { setBusy(false); } }
  if (booked) return <section className="public-booking-confirmation"><span>✓</span><h1>Meeting booked</h1><p>You’re scheduled with {page.workspace.name} on <strong>{new Intl.DateTimeFormat(undefined, { dateStyle: "full", timeStyle: "short" }).format(new Date(booked))}</strong>.</p><small>Time shown in {viewerTimeZone}</small></section>;
  return <section className="public-booking-card"><aside><div className="capture-brand"><span className="brand-mark"><i /><i /><i /></span>LeadFlow</div><p>{page.workspace.name}</p><h1>{page.title}</h1>{page.description && <div>{page.description}</div>}<ul><li>◷ {page.durationMinutes} minutes</li><li>◎ Hosted in {page.timeZone}</li><li>⌖ Displayed in {viewerTimeZone}</li></ul></aside><form onSubmit={book}><h2>Choose a time</h2><label>Date<input type="date" min={today} max={maxDate} value={date} onChange={(event) => { setDate(event.target.value); void findSlots(event.target.value); }} /></label><div className="public-slots">{loading ? <p>Loading available times…</p> : slots.length ? slots.map((slot) => <button type="button" className={selected === slot ? "selected" : ""} key={slot} onClick={() => setSelected(slot)}>{new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(slot))}</button>) : <p>Select a date to see available times.</p>}</div>{selected && <div className="booking-attendee"><label>Your name<input name="name" required minLength={2} /></label><label>Work email<input name="email" type="email" required /></label><label>Notes (optional)<textarea name="notes" rows={3} /></label><button className="primary-button" disabled={busy}>{busy ? "Booking…" : "Confirm meeting"}</button></div>}{error && <div className="inline-error" role="alert">{error}</div>}</form></section>;
}
