ALTER TYPE "LeadActivityType" ADD VALUE 'EMAIL_BOUNCED';
ALTER TYPE "LeadActivityType" ADD VALUE 'EMAIL_COMPLAINED';
ALTER TYPE "LeadActivityType" ADD VALUE 'EMAIL_UNSUBSCRIBED';
ALTER TYPE "LeadActivityType" ADD VALUE 'SUPPRESSION_CHANGED';
